# Process the raw features generated by scope and parse them into the format that the R learner can consume

require('plyr');

rawData = '../Data/general/0202/Features_2015.txt';
parsedData = '../Data/general/0202/Features_2015_parsed.txt';

Raw_Features = read.csv(file=rawData,sep='\t', head=TRUE);

colnames(Raw_Features)[1] = 'candidate';

# Ids = unique(as.character(Raw_Features$Id));
Ids = c("w2");

features_wanted = c("candidate", "NumDistinctTweets", "PositiveRatio", "NonNegativeRatio", "NormalizedNumDistinctTweets");

Features = list();

for(i in 1:length(Ids))
{
	cur = Ids[i]

	Features[[cur]] = subset(Raw_Features,Id==cur,select=-c(Id))[features_wanted];

	names = colnames(Features[[cur]])[2:ncol(Features[[cur]])];
	names = paste(names,cur,sep='_');
	colnames(Features[[cur]])[2:ncol(Features[[cur]])]<-names;

}

Features_A = join_all(Features,by='candidate',type='full');

write.table(Features_A, file=parsedData, sep='\t', row.names=F);