# Process the raw features generated by scope and parse them into the format that the R learner can consume

require('plyr');

rawData = '../Features/201501/Job/All_True_DaysBack_7_Features.txt';
parsedData = '../Features/201501/Job/DaysBack_7_Features_All_candidate_seperated_Absolute';
startMonth = '201101';
endMonth = '201501';

Raw_Features = read.csv(file=rawData,sep='\t');

names = names(Raw_Features);

names[1] = 'candidate';

colnames(Raw_Features) = names;

Features_all = subset(Raw_Features,candidate=='all',select=-c(candidate));
Features_allold = subset(Raw_Features,candidate=='all old',select=-c(candidate));
Features_opening = subset(Raw_Features,candidate=='job opening',select=-c(candidate));
Features_posting = subset(Raw_Features,candidate=='job posting',select=-c(candidate));
Features_opportunity = subset(Raw_Features,candidate=='job opportunity',select=-c(candidate));
Features_hiring = subset(Raw_Features,candidate=='we are hiring',select=-c(candidate));
Features_hashtags = subset(Raw_Features,candidate=='hashtags',select=-c(candidate));

names = names(Features_all);
names = paste(names,'_all',sep='');
names[1]='MonthId';
colnames(Features_all)<-names;

names = names(Features_allold);
names = paste(names,'_allold',sep='');
names[1]='MonthId';
colnames(Features_allold)<-names;

names = names(Features_opening);
names = paste(names,'_opening',sep='');
names[1]='MonthId';
colnames(Features_opening)<-names;

names = names(Features_posting);
names = paste(names,'_posting',sep='');
names[1]='MonthId';
colnames(Features_posting)<-names;

names = names(Features_opportunity);
names = paste(names,'_opportunity',sep='');
names[1]='MonthId';
colnames(Features_opportunity)<-names;

names = names(Features_hiring);
names = paste(names,'_hiring',sep='');
names[1]='MonthId';
colnames(Features_hiring)<-names;

names = names(Features_hashtags);
names = paste(names,'_hashtags',sep='');
names[1]='MonthId';
colnames(Features_hashtags)<-names;

Features_A = join_all(list(Features_all,Features_allold,Features_opening,Features_posting,Features_opportunity,Features_hiring,Features_hashtags),by='MonthId',type='full');

Features_A = subset(Features_A, strtoi(Features_A$MonthId)>=strtoi(startMonth))
Features_A = subset(Features_A, strtoi(Features_A$MonthId)<=strtoi(endMonth))

# Features_Full = Features_Full[2:ncol(Features_Full)];

write.csv(Features_A, file=paste(parsedData,'.csv',sep=''), row.names=F);

# Get normalized features (normalized by past three month rolling average)
output_path_n = paste(parsedData,'Normalized.csv',sep='');
Features_N = data.frame();
for(i in 4:nrow(Features_A))
{
	current = Features_A[i, ];
	header = current[1];
	normalized = current[2:ncol(current)]/(1+colSums(Features_A[(i-3):(i-1), 2:ncol(current)]));
	Features_N = rbind(Features_N, c(header, normalized));
}
write.csv(Features_N, file = output_path_n, row.names=F);

names_a = names(Features_A);
names_a = paste(names_a,'A',sep='_');
names_a[1]='Date';
colnames(Features_A)<-names_a;

names_n = names(Features_N);
names_n = paste(names_n,'N',sep='_');
names_n[1]='Date';
colnames(Features_N)<-names_n;

# Features_Full = join_all(list(Features_A,Features_N),by='Date',type='inner');
Features_Full = Features_A;

# Get delta features
output_path_d = paste(parsedData,'Delta.csv',sep='');
output_path_f = paste(parsedData,'Full.csv',sep='');
Features_D = data.frame();
for(i in 2:nrow(Features_Full))
{
	prev = Features_Full[i-1,];
	current = Features_Full[i,];

	header = current[1];

	delta = current[2:ncol(current)] - prev[2:ncol(current)];
	Features_D = rbind(Features_D, c(header,delta));
}

write.csv(Features_D, file = output_path_d, row.names=F);

names_d = names(Features_D);
names_d = paste(names_d,'D',sep='');
names_d[1]='Date';
colnames(Features_D)<-names_d;


Features_Full = join_all(list(Features_Full,Features_D),by='Date',type='inner');

write.csv(Features_Full, file=output_path_f, row.names=F);